### ISSUE TITLE
teaching modules: project management

### ISSUE THREAD

**Issue by ebeshero** [milnegeneseo/digital-scholarly-editing#3]
During our meeting of Tues. 8/20/2019, we discussed the possibility of adding a project management module, to include tutorials on working with GitHub drafted for our project. We might want to include introductions to Slack and other project management tools, as well as tutorials on cultivating and keeping track of project conversations in such a module. Shall we add this as a new module?

**Comment by WhatTheDickens** [comment]
Added this module to [the wiki page on module structure](https://github.com/milnegeneseo/digital-scholarly-editing/wiki/Module-structure) and added a folder to the repo.
