### ISSUE TITLE
variable typing

### ISSUE THREAD

**Issue by djbpitt** [milnegeneseo/digital-scholarly-editing#4]
https://github.com/milnegeneseo/digital-scholarly-editing/blob/3e3208ffcdea13f05067dbf3f5a6f9e5b8b83c55/TEI_encode/IIIF-from-zoneMapping.xsl#L22

Todo: Add `@as` values for all variables

**Comment by ebeshero** [comment]
AHA! You caught me not typing my variables...how untidy and imprecise of me! @djbpitt

**Comment by ebeshero** [comment]
I'm going to add a little documentation on the style of the input IIIF URL to the comments, too.

**Comment by ebeshero** [comment]
I also had to fix the inevitable namespace issue.  Done with this commit:  https://github.com/milnegeneseo/digital-scholarly-editing/commit/c2abfdcbb554de3956e678dbceabb5f62c0d6f66
